import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    tokenIdentifier: v.string(),
    name: v.string(),
    email: v.string(),
    phone: v.string(),
    accountType: v.union(
      v.literal("hospital"),
      v.literal("supplier"),
      v.literal("hospital_staff"),
      v.literal("admin")
    ),
    verificationStatus: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected")
    ),
    isActive: v.boolean(),
    hospitalId: v.optional(v.id("hospitals")),
    supplierId: v.optional(v.id("suppliers")),
  })
    .index("by_token", ["tokenIdentifier"])
    .index("by_email", ["email"])
    .index("by_verification_status", ["verificationStatus"])
    .index("by_hospital", ["hospitalId"])
    .index("by_supplier", ["supplierId"]),

  hospitals: defineTable({
    name: v.string(),
    contactPerson: v.string(),
    phone: v.string(),
    email: v.string(),
    hospitalCode: v.string(),
    medicalLicenseStorageId: v.optional(v.id("_storage")),
    verificationStatus: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected")
    ),
    createdBy: v.id("users"),
  })
    .index("by_hospital_code", ["hospitalCode"])
    .index("by_verification_status", ["verificationStatus"])
    .index("by_email", ["email"]),

  suppliers: defineTable({
    companyName: v.string(),
    contactPerson: v.string(),
    phone: v.string(),
    email: v.string(),
    cr12StorageId: v.optional(v.id("_storage")),
    categories: v.array(v.id("categories")),
    credits: v.number(),
    verificationStatus: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected")
    ),
    isActive: v.boolean(),
    createdBy: v.id("users"),
  })
    .index("by_verification_status", ["verificationStatus"])
    .index("by_email", ["email"]),

  categories: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    isActive: v.boolean(),
  }).index("by_active", ["isActive"]),

  products: defineTable({
    name: v.string(),
    categoryId: v.id("categories"),
    supplierId: v.id("suppliers"),
    brand: v.optional(v.string()),
    modelSku: v.optional(v.string()),
    unit: v.string(),
    defaultUnitPrice: v.number(),
    moq: v.number(),
    deliveryTime: v.string(),
    countryOfOrigin: v.optional(v.string()),
    warranty: v.optional(v.string()),
    imageStorageIds: v.array(v.id("_storage")),
    description: v.optional(v.string()),
    isActive: v.boolean(),
  })
    .searchIndex("search_name", {
      searchField: "name",
      filterFields: ["categoryId", "supplierId", "isActive"],
    })
    .index("by_category", ["categoryId", "isActive"])
    .index("by_supplier", ["supplierId", "isActive"])
    .index("by_active", ["isActive"]),

  rfqs: defineTable({
    hospitalId: v.id("hospitals"),
    productName: v.string(),
    categoryId: v.id("categories"),
    productId: v.optional(v.id("products")),
    quantity: v.number(),
    unit: v.string(),
    deliveryLocation: v.string(),
    urgency: v.union(
      v.literal("standard"),
      v.literal("urgent"),
      v.literal("emergency")
    ),
    specifications: v.optional(v.string()),
    status: v.union(
      v.literal("open"),
      v.literal("closed"),
      v.literal("fulfilled")
    ),
    createdBy: v.id("users"),
  })
    .index("by_hospital", ["hospitalId", "status"])
    .index("by_category", ["categoryId", "status"])
    .index("by_status", ["status"])
    .index("by_product", ["productId"]),

  quotations: defineTable({
    rfqId: v.id("rfqs"),
    supplierId: v.id("suppliers"),
    productId: v.optional(v.id("products")),
    unitPrice: v.number(),
    totalPrice: v.number(),
    deliveryTime: v.string(),
    notes: v.optional(v.string()),
    isAutoGenerated: v.boolean(),
    status: v.union(
      v.literal("pending"),
      v.literal("accepted"),
      v.literal("rejected")
    ),
    createdBy: v.optional(v.id("users")),
  })
    .index("by_rfq", ["rfqId", "status"])
    .index("by_supplier", ["supplierId", "status"])
    .index("by_rfq_and_supplier", ["rfqId", "supplierId"]),
});
